"""
WAF Detection and Fingerprinting Module — Enhanced

Improvements:
- 25+ WAF signatures
- Multiple probe payloads with escalating severity
- Server header & error-page fingerprinting
- Connection-behaviour heuristics (block, redirect, CAPTCHA)
- Evidence stacking across all probes for higher confidence
"""

import re
import logging
from typing import Dict, List, Optional
from urllib.parse import urlencode, urlparse
import time

logger = logging.getLogger("akha.waf_detector")


class WAFDetector:
    """Detects Web Application Firewalls"""

    def __init__(self, http_client):
        self.client = http_client
        self.signatures = self._load_signatures()
        self.cache = {}


    def _load_signatures(self) -> Dict:
        """Comprehensive WAF signature database"""
        return {
            'cloudflare': {
                'name': 'Cloudflare',
                'headers': ['cf-ray', 'cf-request-id', 'cf-cache-status', 'cf-mitigated'],
                'cookies': ['__cfduid', '__cflb', '__cf_bm', 'cf_clearance'],
                'server_pattern': r'cloudflare',
                'response_patterns': [
                    'Attention Required! | Cloudflare',
                    'ray id:', 'cloudflare', 'cf-ray',
                    'enable JavaScript and cookies to continue',
                    'Performance & security by Cloudflare',
                ],
                'status_codes': [403, 503, 520, 521, 522, 523, 524],
                'priority': 10,
            },
            'akamai': {
                'name': 'Akamai',
                'headers': ['x-akamai-request-id', 'akamai-origin-hop',
                            'x-akamai-transformed', 'x-akamai-session-info'],
                'server_pattern': r'AkamaiGHost|AkamaiNetStorage',
                'response_patterns': ['Reference #', 'akamai', 'Access Denied',
                                      'akamai ghost'],
                'status_codes': [403],
                'priority': 9,
            },
            'aws_waf': {
                'name': 'AWS WAF',
                'headers': ['x-amzn-requestid', 'x-amzn-errortype', 'x-amz-cf-id',
                            'x-amz-apigw-id', 'x-amzn-waf-action'],
                'server_pattern': r'awselb|CloudFront',
                'response_patterns': ['Request blocked', 'AWS', 'AWSWAF',
                                      'automated access to this page has been blocked'],
                'status_codes': [403],
                'priority': 8,
            },
            'imperva': {
                'name': 'Imperva Incapsula',
                'headers': ['x-cdn', 'x-iinfo'],
                'cookies': ['incap_ses', 'visid_incap', 'nlbi_'],
                'response_patterns': ['incapsula', 'imperva',
                                      'Powered By Incapsula',
                                      '_Incapsula_Resource',
                                      'Request unsuccessful. Incapsula incident'],
                'status_codes': [403],
                'priority': 9,
            },
            'modsecurity': {
                'name': 'ModSecurity',
                'headers': ['modsecurity'],
                'server_pattern': r'mod_security|NOYB',
                'response_patterns': [
                    'mod_security', 'modsecurity',
                    'this error was generated by mod_security',
                    'NOYB', 'not acceptable',
                    'rules triggered', 'owasp modsecurity core rule set',
                ],
                'status_codes': [403, 406, 501],
                'priority': 7,
            },
            'f5_bigip': {
                'name': 'F5 BIG-IP ASM',
                'headers': ['x-cnection', 'x-wa-info'],
                'cookies': ['TS', 'BIGipServer', 'f5_cspm'],
                'server_pattern': r'BigIP|BIG-IP|F5',
                'response_patterns': [
                    'The requested URL was rejected',
                    'Please consult with your administrator',
                    'support ID', 'bigip',
                ],
                'status_codes': [403],
                'priority': 8,
            },
            'barracuda': {
                'name': 'Barracuda WAF',
                'headers': ['barra_counter_session'],
                'cookies': ['barra_counter_session', 'BNI__BARRACUDA_LB_COOKIE'],
                'response_patterns': ['barracuda', 'Barracuda Networks'],
                'status_codes': [403],
                'priority': 7,
            },
            'sucuri': {
                'name': 'Sucuri',
                'headers': ['x-sucuri-id', 'x-sucuri-cache', 'x-sucuri-block'],
                'server_pattern': r'Sucuri',
                'response_patterns': ['sucuri', 'cloudproxy',
                                      'Sucuri WebSite Firewall',
                                      'Access Denied - Sucuri Website Firewall'],
                'status_codes': [403],
                'priority': 7,
            },
            'wordfence': {
                'name': 'Wordfence',
                'response_patterns': [
                    'generated by wordfence', 'wordfence',
                    'A potentially unsafe operation has been detected',
                    'Your access to this site has been limited by the site owner',
                    'wfwaf-authcookie',
                ],
                'status_codes': [403, 503],
                'priority': 6,
            },
            'fortinet': {
                'name': 'Fortinet FortiWeb',
                'cookies': ['FORTIWAFSID', 'cookiesession1'],
                'server_pattern': r'FortiWeb|FortiGate',
                'response_patterns': ['fortigate', 'fortiweb',
                                      '.fgd_icon', 'fortiGuard'],
                'status_codes': [403],
                'priority': 7,
            },
            'azure_front_door': {
                'name': 'Azure Front Door / Azure WAF',
                'headers': ['x-azure-ref', 'x-fd-healthprobe', 'x-ms-ref'],
                'response_patterns': [
                    'Azure Front Door', 'Ref A:', 'Ref B:', 'Ref C:',
                ],
                'status_codes': [403],
                'priority': 8,
            },
            'google_cloud_armor': {
                'name': 'Google Cloud Armor',
                'headers': ['x-goog-request-info'],
                'response_patterns': [
                    'Your client has issued a malformed or illegal request',
                    'Error 403 (Forbidden)',
                ],
                'status_codes': [403],
                'priority': 8,
            },
            'citrix_netscaler': {
                'name': 'Citrix NetScaler AppFirewall',
                'headers': ['cneonction', 'nncoection', 'x-nsprotect'],
                'cookies': ['ns_af', 'citrix_ns_id', 'NSC_'],
                'response_patterns': ['ns.af', 'Citrix', 'netscaler',
                                      'ns_af='],
                'status_codes': [403, 302],
                'priority': 7,
            },
            'radware': {
                'name': 'Radware AppWall / DefensePro',
                'headers': ['x-sl-compstate'],
                'response_patterns': [
                    'Radware', 'Unauthorized Activity Has Been Detected',
                    'appwall', 'binarysec',
                ],
                'status_codes': [403],
                'priority': 7,
            },
            'comodo': {
                'name': 'Comodo WAF',
                'server_pattern': r'Protected by COMODO',
                'response_patterns': ['comodo', 'Protected by COMODO WAF'],
                'status_codes': [403],
                'priority': 6,
            },
            'wallarm': {
                'name': 'Wallarm',
                'headers': ['x-wallarm-waf-check'],
                'response_patterns': ['wallarm', 'ngx_wallarm_module'],
                'status_codes': [403],
                'priority': 7,
            },
            'ddos_guard': {
                'name': 'DDoS-Guard',
                'headers': ['ddos-guard'],
                'server_pattern': r'ddos-guard',
                'cookies': ['__ddg1_', '__ddg2_'],
                'response_patterns': ['ddos-guard', 'DDoS protection by'],
                'status_codes': [403, 503],
                'priority': 6,
            },
            'reblaze': {
                'name': 'Reblaze',
                'headers': ['rbzid'],
                'cookies': ['rbzid', 'rbzsessionid'],
                'response_patterns': ['reblaze', 'Access Denied (Reblaze)'],
                'status_codes': [403],
                'priority': 6,
            },
            'stackpath': {
                'name': 'StackPath',
                'headers': ['x-sp-url', 'x-sp-waf-id'],
                'response_patterns': ['StackPath', 'You performed an action that triggered'],
                'status_codes': [403],
                'priority': 6,
            },
            'paloalto': {
                'name': 'Palo Alto Next-Gen Firewall',
                'response_patterns': [
                    'has been blocked in accordance with company policy',
                    'Palo Alto Networks',
                ],
                'status_codes': [403],
                'priority': 7,
            },
            'safe_dog': {
                'name': 'SafeDog',
                'server_pattern': r'safedog',
                'cookies': ['safedog-flow-item'],
                'response_patterns': ['safedog', 'waf.safedog'],
                'status_codes': [403],
                'priority': 5,
            },
            'edgecast': {
                'name': 'Edgecast / Verizon Digital Media',
                'headers': ['x-ec-custom-error'],
                'server_pattern': r'ECD|ECS',
                'response_patterns': ['Edgecast', 'Please retry your request'],
                'status_codes': [400, 403],
                'priority': 6,
            },
            'yunsuo': {
                'name': 'Yunsuo WAF',
                'cookies': ['yunsuo_session_verify'],
                'response_patterns': ['yunsuo.qianxin.com'],
                'status_codes': [403],
                'priority': 5,
            },
        }


    _PROBES = [
        ('xss_1',   '<script>alert(1)</script>'),
        ('xss_2',   '"><img src=x onerror=alert(1)>'),
        ('sqli',    "' OR 1=1 --"),
        ('path',    '/etc/passwd'),
        ('rce',     '; cat /etc/passwd'),
    ]

    def detect(self, url: str) -> Dict:
        """Detect WAF on target URL using multiple probes."""
        domain = urlparse(url).netloc
        if domain in self.cache:
            cached_time, result = self.cache[domain]
            if time.time() - cached_time < 3600:
                return result

        evidence: List[Dict] = []

        baseline_resp = None
        try:
            baseline_resp = self.client.get(url)
            result = self._analyze_response(baseline_resp, 'normal_request')
            if result['detected']:
                evidence.append(result)
        except Exception:
            logger.debug("Baseline WAF probe failed", exc_info=True)

        separator = '&' if '?' in url else '?'
        for label, payload in self._PROBES:
            try:
                probe_url = f"{url}{separator}akhaprobe={payload}"
                resp = self.client.get(probe_url)
                result = self._analyze_response(resp, f'probe_{label}')
                if result['detected']:
                    evidence.append(result)

                if baseline_resp:
                    beh = self._check_behaviour(baseline_resp, resp, label)
                    if beh['detected']:
                        evidence.append(beh)
            except Exception:
                evidence.append({
                    'detected': True,
                    'name': 'Unknown WAF (Connection blocked)',
                    'confidence': 50,
                    'method': f'connection_block_{label}',
                })

        timing = self._detect_from_timing(url)
        if timing['detected']:
            evidence.append(timing)

        final = self._aggregate_results(evidence)
        self.cache[domain] = (time.time(), final)
        return final


    def _check_behaviour(self, baseline, probe_resp, label: str) -> Dict:
        """Compare probe response to baseline for WAF behavioural signals."""
        confidence = 0
        name = 'Unknown WAF'

        if baseline.status_code < 400 and probe_resp.status_code in (403, 406, 429, 444, 501, 503):
            confidence += 40

        if probe_resp.status_code in (301, 302, 307):
            location = probe_resp.headers.get('Location', '').lower()
            if any(kw in location for kw in ['captcha', 'blocked', 'challenge', 'verify', 'waf']):
                confidence += 35

        bl_size = len(baseline.text) if baseline.text else 0
        pr_size = len(probe_resp.text) if probe_resp.text else 0
        if bl_size > 500 and pr_size < bl_size * 0.3:
            confidence += 20

        body_lower = probe_resp.text[:8192].lower() if probe_resp.text else ''
        block_kws = [
            'access denied', 'request blocked', 'forbidden',
            'not acceptable', 'security policy', 'violation',
            'your request has been blocked', 'suspicious activity',
            'automated request', 'web application firewall',
            'your ip has been blocked', 'please verify you are human',
            'captcha', 'challenge', 'bot detection',
        ]
        for kw in block_kws:
            if kw in body_lower:
                confidence += 10
                break

        if confidence >= 30:
            return {
                'detected': True,
                'name': name,
                'confidence': min(confidence, 100),
                'method': f'behaviour_{label}',
            }
        return {'detected': False}

    def _analyze_response(self, response, method: str) -> Dict:
        """Analyze response for WAF signatures"""
        max_confidence = 0
        detected_waf = None
        detected_sig = None

        resp_headers_lower = {h.lower(): v for h, v in response.headers.items()}
        server_header = resp_headers_lower.get('server', '')
        body_lower = response.text[:8192].lower() if response.text else ''

        for waf_id, sig in self.signatures.items():
            confidence = 0

            for header in sig.get('headers', []):
                if header.lower() in resp_headers_lower:
                    confidence += 30

            server_re = sig.get('server_pattern')
            if server_re and re.search(server_re, server_header, re.I):
                confidence += 25

            for cookie_name in sig.get('cookies', []):
                for ck in response.cookies:
                    if cookie_name.lower() in ck.lower():
                        confidence += 25
                        break

            if response.status_code in sig.get('status_codes', []):
                confidence += 10

            for pattern in sig.get('response_patterns', []):
                if pattern.lower() in body_lower:
                    confidence += 20
                    break

            if confidence > max_confidence:
                max_confidence = confidence
                detected_waf = sig['name']
                detected_sig = waf_id

        if max_confidence >= 25:
            return {
                'detected': True,
                'name': detected_waf,
                'signature_id': detected_sig,
                'confidence': min(max_confidence, 100),
                'method': method,
            }

        return {'detected': False}

    def _detect_from_timing(self, url: str) -> Dict:
        """Detect WAF using timing analysis"""
        try:
            start = time.time()
            self.client.get(url)
            normal_time = time.time() - start

            separator = '&' if '?' in url else '?'
            start = time.time()
            self.client.get(f"{url}{separator}test=<script>alert(1)</script>")
            malicious_time = time.time() - start

            if malicious_time > normal_time * 2.5 and malicious_time > 1.5:
                return {
                    'detected': True,
                    'name': 'Unknown WAF (Timing-based)',
                    'confidence': 55,
                    'method': 'timing_analysis',
                }
        except Exception:
            logger.debug("Timing-based WAF detection failed", exc_info=True)
        return {'detected': False}

    def _aggregate_results(self, results: List[Dict]) -> Dict:
        """Aggregate multiple detection results with evidence stacking."""
        if not results:
            return {'detected': False, 'name': None, 'confidence': 0}

        waf_scores: Dict[str, int] = {}
        waf_methods: Dict[str, List[str]] = {}
        waf_conf_values: Dict[str, List[int]] = {}
        for r in results:
            name = r.get('name', 'Unknown WAF')
            conf = r.get('confidence', 0)
            waf_scores[name] = waf_scores.get(name, 0) + conf
            waf_methods.setdefault(name, []).append(r.get('method', ''))
            waf_conf_values.setdefault(name, []).append(conf)

        best_name = max(waf_scores, key=waf_scores.get)
        best_conf = min(waf_scores[best_name], 100)

        if best_name.startswith('Unknown') and len(waf_scores) > 1:
            for name, score in sorted(waf_scores.items(), key=lambda x: x[1], reverse=True):
                if not name.startswith('Unknown'):
                    best_name = name
                    best_conf = min(score, 100)
                    break

        return {
            'detected': True,
            'name': best_name,
            'confidence': best_conf,
            'method': ', '.join(waf_methods.get(best_name, [])),
            'confidence_score': {
                'weighted_total': best_conf,
                'evidence_count': len(waf_methods.get(best_name, [])),
                'avg_signal': int(sum(waf_conf_values.get(best_name, [0])) / max(len(waf_conf_values.get(best_name, [0])), 1)),
            },
            'evidence': [
                {
                    'method': r.get('method', ''),
                    'confidence': int(r.get('confidence', 0)),
                    'name': r.get('name', ''),
                }
                for r in results
                if r.get('name') == best_name
            ],
        }


    def get_bypass_techniques(self, waf_name: str) -> List[str]:
        """Get bypass techniques for specific WAF"""
        techniques = {
            'Cloudflare': [
                'case_variation', 'encoding_variation',
                'comment_injection', 'space_variation', 'backtick_usage',
            ],
            'Akamai': [
                'unicode_encoding', 'parameter_pollution', 'multipart_bypass',
            ],
            'AWS WAF': [
                'case_mutation', 'encoding_mix', 'null_byte_injection',
            ],
            'Imperva Incapsula': [
                'parameter_cloaking', 'encoding_variation', 'http_verb_tampering',
            ],
            'ModSecurity': [
                'encoding_nested', 'case_variation', 'comment_injection',
            ],
            'F5 BIG-IP ASM': [
                'case_variation', 'chunked_encoding', 'multipart_bypass',
            ],
        }
        return techniques.get(waf_name, ['generic_bypass', 'encoding_variation'])
